import { ConfigModule } from '@nestjs/config';

import { AppConfigByAppEnv, AppConfigVariables, AppEnv } from '@/app.types';

ConfigModule.forRoot();

export const APP_ENV = process.env.APP_ENV as AppEnv;

export const LOCAL_MONGODB_CONNECTION_STRING =
  process.env.MONGODB_CONNECTION_STRING;
export const DEV_MONGODB_CONNECTION_STRING =
  process.env.MONGODB_CONNECTION_STRING;
export const PROD_MONGODB_CONNECTION_STRING =
  process.env.MONGODB_CONNECTION_STRING;

export const LOCAL_STRIPE_API_KEY = process.env.STRIPE_API_KEY;
export const DEV_STRIPE_API_KEY = process.env.STRIPE_API_KEY;
export const PROD_STRIPE_API_KEY = process.env.STRIPE_API_KEY;

export const LOCAL_JWT_SECRET_KEY = process.env.JWT_SECRET_KEY;
export const DEV_JWT_SECRET_KEY = process.env.JWT_SECRET_KEY;
export const PROD_JWT_SECRET_KEY = process.env.JWT_SECRET_KEY;

export const LOCAL_CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
export const DEV_CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
export const PROD_CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;

export const LOCAL_CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
export const DEV_CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
export const PROD_CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;

export const LOCAL_CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
export const DEV_CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
export const PROD_CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;

const config: AppConfigByAppEnv = {
  local: {
    MONGODB_CONNECTION_STRING: LOCAL_MONGODB_CONNECTION_STRING,
    STRIPE_API_KEY: LOCAL_STRIPE_API_KEY,
    JWT_SECRET_KEY: LOCAL_JWT_SECRET_KEY,
    CLOUDINARY_API_KEY: LOCAL_CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: LOCAL_CLOUDINARY_API_SECRET,
    CLOUDINARY_CLOUD_NAME: LOCAL_CLOUDINARY_CLOUD_NAME,
  },
  development: {
    MONGODB_CONNECTION_STRING: DEV_MONGODB_CONNECTION_STRING,
    STRIPE_API_KEY: DEV_STRIPE_API_KEY,
    JWT_SECRET_KEY: DEV_JWT_SECRET_KEY,
    CLOUDINARY_API_KEY: DEV_CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: DEV_CLOUDINARY_API_SECRET,
    CLOUDINARY_CLOUD_NAME: DEV_CLOUDINARY_CLOUD_NAME,
  },
  production: {
    MONGODB_CONNECTION_STRING: PROD_MONGODB_CONNECTION_STRING,
    STRIPE_API_KEY: PROD_STRIPE_API_KEY,
    JWT_SECRET_KEY: PROD_JWT_SECRET_KEY,
    CLOUDINARY_API_KEY: PROD_CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: PROD_CLOUDINARY_API_SECRET,
    CLOUDINARY_CLOUD_NAME: PROD_CLOUDINARY_CLOUD_NAME,
  },
};

export const CURRENT_APP_CONFIG = config[APP_ENV];

export const {
  MONGODB_CONNECTION_STRING,
  STRIPE_API_KEY,
  JWT_SECRET_KEY,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_CLOUD_NAME,
} = CURRENT_APP_CONFIG;

export const AppConfig = (): AppConfigVariables => CURRENT_APP_CONFIG;

export default AppConfig;
